apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-service
  namespace: game-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-service
  template:
    metadata:
      labels:
        app: game-service
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: game-service
        image: registry.gitlab.com/game-metrics/backend/game-service:latest
        imagePullPolicy: Always
        env:
        - name: DOMAIN_NAME
          value: localhost
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-volume
          mountPath: /app/config.yml
          subPath: config.yml
      volumes:
      - name: config-volume
        configMap:
          name: game-service-config
