apiVersion: v1
kind: ConfigMap
metadata:
  name: game-service-config
  namespace: game-metrics
data:
  config.yml: |
    port: 8080
    public_uri_prefix: /api/games
    internal_uri_prefix: /internal
    jwks_endpoint: http://auth-service:8080/internal/jwks
    database:
      host: game-service-db
      port: 5432
      user: postgres
      password: postgres
      dbname: gm_games
      sslmode: disable
      timezone: Europe/Moscow
    amqp:
      host: rabbitmq
      port: 5672
      user: guest
      password: guest
      timeout: 5s

