services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: ./build/package/Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    networks:
      - gm_backend_net
    restart: on-failure

networks:
  gm_backend_net:
