apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: dev-game-metrics-tls
spec:
  acme:
    email: czwetkow.serega@yandex.ru
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: dev-game-metrics-tls
    solvers:
    - http01:
        ingress:
          class: nginx
