services:
  activity-service:
      environment:
        - DOMAIN_NAME=localhost
      build:
        context: ./
        dockerfile: ./activity-service/build/package/Dockerfile
      container_name: activity-service
      networks:
        - gm-backend-net
        - activity-service-net
      restart: always
      depends_on:
        - activity-service-db
        - rabbitmq
      volumes:
        - ./activity-service/configs/config.yml:/app/config.yml:ro

  activity-service-db:
    build:
      dockerfile: ./auth-service/build/package/db.Dockerfile
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gm_activity
    container_name: activity-service-db
    ports:
      - "5434:5432"
    networks:
      - activity-service-net
    restart: always

networks:
  activity-service-net:
