services:
  auth-service:
      environment:
        - DOMAIN_NAME=localhost
      build:
        context: ./
        dockerfile: ./auth-service/build/package/Dockerfile
      container_name: auth-service
      networks:
        - gm-backend-net
        - auth-service-net
      restart: always
      depends_on:
        - auth-service-db
        - rabbitmq
      volumes:
        - ./auth-service/configs/config.yml:/app/config.yml:ro
        - ./auth-service/configs/public.pem:/app/public.pem:ro
        - ./auth-service/configs/private.pem:/app/private.pem:ro

  auth-service-db:
    build:
      dockerfile: ./auth-service/build/package/db.Dockerfile
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gm_auth
    container_name: auth-service-db
    ports:
      - "5433:5432"
    networks:
      - auth-service-net
    restart: always

networks:
  auth-service-net:
