port: 8080
base_uri_prefix: /api/auth/
auth_tokens:
  jwt_expiration_time: 1440
  refresh_token_expiration_time: 9999
database:
  host: auth-service-db
  port: 5432
  user: postgres
  password: postgres
  dbname: gm_auth
  sslmode: disable
  timezone: Europe/Moscow
