apiVersion: v1
kind: Service
metadata:
  name: players-service-db
  namespace: game-metrics
spec:
  selector:
    app: players-service-db
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
