apiVersion: apps/v1
kind: Deployment
metadata:
  name: players-service
  namespace: game-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: players-service
  template:
    metadata:
      labels:
        app: players-service
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: players-service
        image: registry.gitlab.com/game-metrics/backend/players-service:latest
        imagePullPolicy: Always
        env:
        - name: DOMAIN_NAME
          value: localhost
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-volume
          mountPath: /app/config.yml
          subPath: config.yml
      volumes:
      - name: config-volume
        configMap:
          name: players-service-config
