port: 8080
public_uri_prefix: /api/activity
internal_uri_prefix: /internal
database:
  host: activity-service-db
  port: 5432
  user: postgres
  password: postgres
  dbname: gm_activity
  sslmode: disable
  timezone: Europe/Moscow
amqp:
  host: rabbitmq
  port: 5672
  user: guest
  password: guest
  timeout: 5s
