apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: game-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: auth-service
        image: registry.gitlab.com/game-metrics/backend/auth-service:latest
        imagePullPolicy: Always
        env:
        - name: DOMAIN_NAME
          value: localhost
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-volume
          mountPath: /config
        command: ["./auth-service", "--config", "/config/config.yml"]
      volumes:
      - name: config-volume
        configMap:
          name: auth-service-config
