apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: game-metrics
data:
  config.yml: |
    port: 8080
    public_uri_prefix: /api/auth
    internal_uri_prefix: /internal
    jwt_token:
      public_key_filepath: /config/public.pem
      private_key_filepath: /config/private.pem
      jwt_expiration_time: 24h
      refresh_token_expiration_time: 8760h
    database:
      host: auth-service-db
      port: 5432
      user: postgres
      password: postgres
      dbname: gm_auth
      sslmode: disable
      timezone: Europe/Moscow
    amqp:
      host: rabbitmq
      port: 5672
      user: guest
      password: guest
      timeout: 5s
  public.pem: |
    -----BEGIN PUBLIC KEY-----
    MCowBQYDK2VwAyEACc0GJyYAmQ2bTRJGS2azqsbc5VUQNYMNQyl0x8dXFOU=
    -----END PUBLIC KEY-----
  private.pem: |
    -----BEGIN PRIVATE KEY-----
    MC4CAQAwBQYDK2VwBCIEIFfuqk4aM8X3qqxag4fTpk4a8pcPqmvl/HA0u/nuD5Z7
    -----END PRIVATE KEY-----
