apiVersion: apps/v1
kind: Deployment
metadata:
  name: activity-service-db
  namespace: game-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activity-service-db
  template:
    metadata:
      labels:
        app: activity-service-db
    spec:
      containers:
      - name: postgres
        image: postgres:17
        env:
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: gm_activity
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: db-init
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: db-init
        configMap:
          name: activity-db-init
