apiVersion: v1
kind: Service
metadata:
  name: activity-service-db
  namespace: game-metrics
spec:
  selector:
    app: activity-service-db
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
