apiVersion: v1
kind: Service
metadata:
  name: activity-service
  namespace: game-metrics
spec:
  selector:
    app: activity-service
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
